### ISSUE TITLE
RefreshAllNodes not catching issues

### ISSUE THREAD

**Issue by imtrobin** [nachomonkey/RefreshAllNodes#3]
Hi, I tried the plugin to refresh all the blueprints, one of them has nodes that is no longer valid because it is changed in C++. While it refreshes, it didn't catch or flag the error.  It would be helpful if it can detect which blueprint (s) that has issues.

I notice there is FKismetEditorUtilities::CompileBlueprint that might be helpful. If there is an warning in compilation, have an option to open the blueprint so we might be alerted to which ones have failed. Also, UEditorLoadingAndSavingUtils::SavePackages might fail, so it would be helpful to flag it.

On a large project, I'm having memory issues. Maybe save each blueprint after refresh immediately instead of collecting them? Adding a sleep and UEngine::ForceGarbageCollection might help.

**Comment by nachomonkey** [comment]
I made this commit https://github.com/nachomonkey/RefreshAllNodes/commit/81175681ffb37461f061043e63371a1c1366e480, which adds the ability to compile the blueprints. It is the default behavior now. I also made it notify you when there are blueprints with errors as well as a way to see and open the failing blueprints. Now the plugin displays helpful notifications, and it will indicate if the `UEditorLoadingAndSavingUtils::SavePackages` call fails.

Unfortunately, I couldn't reduce the plugin's memory usage... although the plugin isn't hanging onto any of the assets, so they should just be garbage collected. It still consumes some memory. Do note: If you have "Refresh Level Blueprints" enabled, it will consume *significantly* more memory than otherwise.

I tried saving the blueprints one by one instead of all at once; it had no impact on memory usage. However, it was significantly slower, so I kept it saving in parallel.

I hope this update helps!
