### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CoolOppo** [nachomonkey/RefreshAllNodes#6]
```
Assertion failed: InContext.Struct [File:D:\build\++UE5\Sync\Engine\Plugins\Runtime\PropertyAccess\Source\PropertyAccessEditor\Private\PropertyAccessEditor.cpp] [Line: 180]

UnrealEditor_PropertyAccessEditor
UnrealEditor_PropertyAccessEditor
UnrealEditor_PropertyAccessEditor
UnrealEditor_AnimGraph
UnrealEditor_AnimGraph
UnrealEditor_BlueprintGraph
UnrealEditor_UnrealEd
UnrealEditor_RefreshAllNodes!FRefreshAllNodesModule::FindAndRefreshBlueprints() [C:\Users\Winston\Documents\Unreal Projects\RAN_5_10_Build\Plugins\RefreshAllNodes\Source\RefreshAllNodes\Private\RefreshAllNodes.cpp:276]
UnrealEditor_RefreshAllNodes!FRefreshAllNodesModule::RefreshAllButton_Clicked() [C:\Users\Winston\Documents\Unreal Projects\RAN_5_10_Build\Plugins\RefreshAllNodes\Source\RefreshAllNodes\Private\RefreshAllNodes.cpp:197]
UnrealEditor_RefreshAllNodes!TBaseRawMethodDelegateInstance<0,FRefreshAllNodesModule,void __cdecl(void),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:475]
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_Slate
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
UnrealEditor_ApplicationCore
user32
user32
UnrealEditor_ApplicationCore
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```

**Comment by nachomonkey** [comment]
Hello and thank you for reporting this.

The crash report you included suggests that the Editor is crashing when the plugin is invoking UE's `RefreshAllNodes` function on one of your Animation Blueprint assets. From my testing, there doesn't seem to be a correlation between refreshing AnimBlueprints and crashing; but perhaps they are more likely to cause a crash.

You could look at the editor logs after the crash (at path *YourProject*/Saved/Logs/*YourProject*.log ). Near the end, right before the crash occurs there should be some logs from my plugin marked as `LogRefreshAllNodes` that say which blueprints were being refreshed. The last RefreshAllNodes log should happen right before the crash and that one will tell you which asset was causing the crash.

You could see if there is anything seemingly problematic about the asset... like if it somehow looks corrupted, and you could fix it that way to stop the crash?

I'm also curious if it's just that one asset making it crash or if other AnimBPs would do it too...

Anyway, if that doesn't solve it:
If you go under `Project Settings` -> `Refresh All Nodes`, there is the `Exclude Blueprint Paths` array which can exclude the containing folder of the problematic asset, or theoretically maybe even be used to exclude that *specific* asset.

Otherwise, I could add a way to just exclude all AnimBPs, or maybe exclude entire BP-subclasses... yeah that feature really should've been there all along :)

Hope it helps and sorry for the crashing.
